"use client";

import { useEffect, useState } from "react";
import { jsPDF } from "jspdf";
import AppShell from "@/components/AppShell";
import PageHeader from "@/components/ui/PageHeader";
import StatCard from "@/components/ui/StatCard";
import { useIncidentStore } from "@/lib/incident-store";
import { formatAreaM2, formatDateTimeAZT } from "@/lib/mock-data";
import { useLanguage } from "@/lib/useLanguage";
import {
  FileBarChart,
  Maximize2,
  Droplets,
  ShieldAlert,
  Percent,
  CheckCircle2,
  Download,
  History,
  FileSpreadsheet,
  FileText,
} from "lucide-react";

type SavedReport = {
  id: string;
  incidentId: string;
  incidentDisplayId: string;
  incidentTitle: string;
  team: string;
  estimatedCostUsd: number;
  generatedBy: string;
  generatedAt: string;
};

export default function ReportsPage() {
  return (
    <AppShell active="reports">
      <ReportsContent />
    </AppShell>
  );
}

function ReportsContent() {
  const { t } = useLanguage();
  const { report, incidents, stats } = useIncidentStore();
  const [previewOpen, setPreviewOpen] = useState(false);
  const [savedReports, setSavedReports] = useState<SavedReport[]>([]);
  const [reportsLoading, setReportsLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;
    fetch("/api/reports", { cache: "no-store" })
      .then((res) => (res.ok ? res.json() : []))
      .then((data) => {
        if (!cancelled) setSavedReports(Array.isArray(data) ? data : []);
      })
      .catch(() => {})
      .finally(() => {
        if (!cancelled) setReportsLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  const riskDist = {
    HIGH: incidents.filter((i) => i.risk === "HIGH").length,
    MEDIUM: incidents.filter((i) => i.risk === "MEDIUM").length,
    LOW: incidents.filter((i) => i.risk === "LOW").length,
  };

  // Both exports below are fleet-wide aggregate stats only (counts, areas,
  // risk mix, report history) — not the per-incident AI/satellite/drift
  // narrative. See IncidentDetailsPanel.tsx's generateIncidentPdf for that
  // template and its data-source notes.
  const exportCsv = () => {
    const csvEscape = (value: string | number) => {
      const s = String(value);
      return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
    };
    const lines: string[] = [
      "SeaSentry Reports Overview",
      "",
      "Metric,Value",
      `Total Incidents,${report.totalIncidents}`,
      `Total Detected Area (m2),${report.totalDetectedAreaM2}`,
      `Total Cleaned Area (m2),${report.totalCleanedAreaM2}`,
      `High-Risk Incidents,${report.highRiskCount}`,
      `Average AI Confidence (%),${report.averageAiConfidence}`,
      `Resolved Incidents,${report.resolvedCount}`,
      "",
      "Risk,Count",
      ...(["HIGH", "MEDIUM", "LOW"] as const).map((level) => `${level},${riskDist[level]}`),
      "",
      "Incident,Team,Cost (USD),Generated By,Generated At",
      ...savedReports.map((r) =>
        [
          csvEscape(`${r.incidentDisplayId} - ${r.incidentTitle}`),
          csvEscape(r.team),
          r.estimatedCostUsd,
          csvEscape(r.generatedBy),
          csvEscape(`${formatDateTimeAZT(r.generatedAt)} AZT`),
        ].join(",")
      ),
    ];

    const blob = new Blob([lines.join("\n")], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `seasentry-reports-${new Date().toISOString().slice(0, 10)}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const exportPdf = () => {
    const doc = new jsPDF();
    let y = 20;
    const line = (text: string, size = 11, bold = false, gap = 7) => {
      doc.setFontSize(size);
      doc.setFont("helvetica", bold ? "bold" : "normal");
      doc.text(text, 14, y);
      y += gap;
    };
    const ensureSpace = (needed = 12) => {
      if (y + needed > 280) {
        doc.addPage();
        y = 20;
      }
    };

    line("SeaSentry — Operational Reports Overview", 18, true, 10);
    doc.setDrawColor(200);
    doc.line(14, y - 4, 196, y - 4);
    y += 2;
    line(`Generated: ${formatDateTimeAZT(new Date().toISOString())} AZT`, 10);
    y += 4;

    line("Summary", 13, true, 8);
    line(`Total incidents: ${report.totalIncidents}`);
    line(`Detected area: ${formatAreaM2(report.totalDetectedAreaM2)}`);
    line(`Cleaned area: ${formatAreaM2(report.totalCleanedAreaM2)}`);
    line(`High-risk incidents: ${report.highRiskCount}`);
    line(`Average AI confidence: ${report.averageAiConfidence}%`);
    line(`Resolved incidents: ${report.resolvedCount}`);
    y += 4;

    line("Risk distribution", 13, true, 8);
    (["HIGH", "MEDIUM", "LOW"] as const).forEach((level) => {
      const count = riskDist[level];
      const pct = report.totalIncidents ? Math.round((count / report.totalIncidents) * 100) : 0;
      line(`${level}: ${count} (${pct}%)`);
    });
    y += 4;

    line("Report history", 13, true, 8);
    if (savedReports.length === 0) {
      line("No reports generated yet.");
    } else {
      savedReports.forEach((r) => {
        ensureSpace();
        line(`${r.incidentDisplayId} · ${r.incidentTitle}`, 10, true, 5);
        line(
          `  ${r.team} · $${r.estimatedCostUsd.toLocaleString("en-US")} · ${r.generatedBy} · ${formatDateTimeAZT(r.generatedAt)} AZT`,
          9,
          false,
          7
        );
      });
    }

    doc.setFontSize(9);
    doc.setFont("helvetica", "italic");
    doc.text(
      "Demo document generated by SeaSentry — an oil-spill intelligence platform. Figures are simulated.",
      14,
      290
    );

    doc.save(`seasentry-reports-overview-${new Date().toISOString().slice(0, 10)}.pdf`);
  };

  return (
    <>
      <div className="dashboard-scroll">
        <PageHeader
          title={t.reports.title}
          subtitle={t.reports.subtitle}
          actions={
            <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
              <button
                type="button"
                onClick={exportCsv}
                style={{
                  display: "inline-flex",
                  alignItems: "center",
                  gap: 8,
                  background: "transparent",
                  color: "var(--text-primary)",
                  border: "1px solid var(--glass-border)",
                  borderRadius: 8,
                  padding: "10px 14px",
                  fontWeight: 650,
                  fontSize: 13,
                  cursor: "pointer",
                  fontFamily: "inherit",
                }}
              >
                <FileSpreadsheet size={15} /> {t.reports.exportCsv}
              </button>
              <button
                type="button"
                onClick={exportPdf}
                style={{
                  display: "inline-flex",
                  alignItems: "center",
                  gap: 8,
                  background: "transparent",
                  color: "var(--text-primary)",
                  border: "1px solid var(--glass-border)",
                  borderRadius: 8,
                  padding: "10px 14px",
                  fontWeight: 650,
                  fontSize: 13,
                  cursor: "pointer",
                  fontFamily: "inherit",
                }}
              >
                <FileText size={15} /> {t.reports.exportPdf}
              </button>
              <button
                type="button"
                onClick={() => setPreviewOpen(true)}
                style={{
                  display: "inline-flex",
                  alignItems: "center",
                  gap: 8,
                  background: "var(--accent)",
                  color: "var(--bg-elevated)",
                  border: "none",
                  borderRadius: 8,
                  padding: "10px 14px",
                  fontWeight: 650,
                  fontSize: 13,
                  cursor: "pointer",
                  fontFamily: "inherit",
                }}
              >
                <Download size={15} /> {t.reports.generateReport}
              </button>
            </div>
          }
        />

        <section
          style={{ display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: 12 }}
          className="report-stat-grid"
        >
          <StatCard label={t.reports.totalIncidents} value={report.totalIncidents} icon={<FileBarChart size={15} />} />
          <StatCard
            label={t.reports.totalDetectedArea}
            value={formatAreaM2(report.totalDetectedAreaM2)}
            icon={<Maximize2 size={15} />}
          />
          <StatCard
            label={t.reports.totalCleanedArea}
            value={formatAreaM2(report.totalCleanedAreaM2)}
            accent="var(--color-low)"
            icon={<Droplets size={15} />}
          />
          <StatCard
            label={t.reports.highRiskIncidents}
            value={report.highRiskCount}
            accent="var(--color-med)"
            icon={<ShieldAlert size={15} />}
          />
          <StatCard
            label={t.reports.averageAiConfidence}
            value={`${report.averageAiConfidence}%`}
            accent="var(--accent)"
            icon={<Percent size={15} />}
          />
          <StatCard
            label={t.reports.resolvedIncidents}
            value={report.resolvedCount}
            accent="var(--color-low)"
            icon={<CheckCircle2 size={15} />}
          />
        </section>

        <div style={{ display: "grid", gridTemplateColumns: "1.2fr 1fr", gap: 16 }} className="report-panels">
          <div className="panel panel-static">
            <div className="panel-header">
              <span className="panel-title">{t.reports.operationalSnapshot}</span>
            </div>
            <div className="panel-body" style={{ padding: 16, display: "grid", gap: 12 }}>
              <Row label={t.reports.activeIncidents} value={String(stats.active)} />
              <Row label={t.reports.underReview} value={String(stats.underReview)} />
              <Row label={t.reports.resolved} value={String(stats.resolved)} />
              <Row label={t.reports.avgResponseLatency} value={`${report.avgResponseTimeMin} min`} />
              <Row label={t.reports.datasetScope} value={t.reports.datasetScopeValue} />
            </div>
          </div>

          <div className="panel panel-static">
            <div className="panel-header">
              <span className="panel-title">{t.reports.riskDistribution}</span>
            </div>
            <div className="panel-body" style={{ padding: 16, display: "grid", gap: 14 }}>
              {(["HIGH", "MEDIUM", "LOW"] as const).map((level) => {
                const count = riskDist[level];
                const pct = report.totalIncidents
                  ? Math.round((count / report.totalIncidents) * 100)
                  : 0;
                const color =
                  level === "HIGH"
                    ? "var(--color-high)"
                    : level === "MEDIUM"
                      ? "var(--color-med)"
                      : "var(--color-low)";
                return (
                  <div key={level}>
                    <div style={{ display: "flex", justifyContent: "space-between", fontSize: 12, marginBottom: 6 }}>
                      <span>{t.risk[level]}</span>
                      <span style={{ color: "var(--text-secondary)" }}>
                        {count} ({pct}%)
                      </span>
                    </div>
                    <div style={{ height: 8, borderRadius: 4, background: "rgba(43,45,66,0.08)" }}>
                      <div style={{ width: `${pct}%`, height: "100%", borderRadius: 4, background: color }} />
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>

        <div className="panel panel-static" style={{ marginTop: 16 }}>
          <div className="panel-header">
            <span className="panel-title">
              <History size={13} style={{ verticalAlign: -2, marginRight: 6 }} />
              {t.reports.reportHistory}
            </span>
            <span style={{ fontSize: 11, color: "var(--text-tertiary)" }}>
              {reportsLoading ? t.common.loading : t.reports.generatedCount(savedReports.length)}
            </span>
          </div>
          <div className="panel-body" style={{ overflowX: "auto" }}>
            {!reportsLoading && savedReports.length === 0 ? (
              <div style={{ padding: 20, fontSize: 13, color: "var(--text-secondary)" }}>
                {t.reports.noReportsYet}
              </div>
            ) : (
              <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 13 }}>
                <thead>
                  <tr style={{ textAlign: "left", color: "var(--text-tertiary)", fontSize: 11 }}>
                    <th style={{ padding: "8px 12px" }}>{t.reports.colIncident}</th>
                    <th style={{ padding: "8px 12px" }}>{t.reports.colTeam}</th>
                    <th style={{ padding: "8px 12px" }}>{t.reports.colCost}</th>
                    <th style={{ padding: "8px 12px" }}>{t.reports.colGeneratedBy}</th>
                    <th style={{ padding: "8px 12px" }}>{t.reports.colGeneratedAt}</th>
                  </tr>
                </thead>
                <tbody>
                  {savedReports.map((r) => (
                    <tr key={r.id} style={{ borderTop: "1px solid var(--border-muted)" }}>
                      <td style={{ padding: "10px 12px" }}>
                        {r.incidentDisplayId} · {r.incidentTitle}
                      </td>
                      <td style={{ padding: "10px 12px" }}>{r.team}</td>
                      <td style={{ padding: "10px 12px" }}>${r.estimatedCostUsd.toLocaleString("en-US")}</td>
                      <td style={{ padding: "10px 12px" }}>{r.generatedBy}</td>
                      <td style={{ padding: "10px 12px" }}>{formatDateTimeAZT(r.generatedAt)} AZT</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        </div>

        {previewOpen && (
          <>
            <div
              onClick={() => setPreviewOpen(false)}
              style={{ position: "fixed", inset: 0, background: "rgba(0,0,0,0.5)", zIndex: 80 }}
            />
            <div
              role="dialog"
              style={{
                position: "fixed",
                top: "50%",
                left: "50%",
                transform: "translate(-50%, -50%)",
                width: "min(520px, calc(100vw - 32px))",
                background: "var(--bg-elevated)",
                border: "1px solid var(--glass-border)",
                borderRadius: 12,
                padding: 24,
                zIndex: 90,
              }}
            >
              <h2 style={{ margin: "0 0 8px", fontSize: 18 }}>{t.reports.previewTitle}</h2>
              <p style={{ margin: "0 0 16px", color: "var(--text-secondary)", fontSize: 13, lineHeight: 1.5 }}>
                {t.reports.previewBody}
              </p>
              <div style={{ display: "grid", gap: 8, fontSize: 13, marginBottom: 18 }}>
                <Row label={t.reports.totalIncidents} value={String(report.totalIncidents)} />
                <Row label={t.reports.detectedArea} value={formatAreaM2(report.totalDetectedAreaM2)} />
                <Row label={t.reports.cleanedArea} value={formatAreaM2(report.totalCleanedAreaM2)} />
                <Row label={t.reports.avgAiConfidence} value={`${report.averageAiConfidence}%`} />
              </div>
              <button
                type="button"
                onClick={() => setPreviewOpen(false)}
                style={{
                  width: "100%",
                  padding: "10px 14px",
                  borderRadius: 8,
                  border: "1px solid var(--glass-border)",
                  background: "transparent",
                  color: "var(--text-primary)",
                  cursor: "pointer",
                  fontFamily: "inherit",
                }}
              >
                {t.reports.close}
              </button>
            </div>
          </>
        )}
      </div>

      <style>{`
        @media (max-width: 1000px) {
          .report-stat-grid { grid-template-columns: repeat(2, minmax(0, 1fr)) !important; }
          .report-panels { grid-template-columns: 1fr !important; }
        }
      `}</style>
    </>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div
      style={{
        display: "flex",
        justifyContent: "space-between",
        gap: 12,
        padding: "8px 0",
        borderBottom: "1px solid var(--border-muted)",
      }}
    >
      <span style={{ color: "var(--text-secondary)", fontSize: 13 }}>{label}</span>
      <span style={{ fontWeight: 600, fontSize: 13 }}>{value}</span>
    </div>
  );
}
